### PR TITLE
Fix using the wrong account to get chatters

### PR DESCRIPTION
**Pull request by liquidnya**
### Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you run `eslint` on the code and resolved any errors?
- [x] Have you run `npm test` and all tests are passing?
- [ ] Have you added new tests for any new functions created?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

Fixes a bug where the broadcaster token was not used to get chatters, but instead the bot token was used even though the broadcaster has the `moderator:read:chatters` scope and the bot account does not.

This is because even though the `chatters` intend is given to the correct account, the API was called like this:
```ts
let page = await ctx.chat.getChatters(this.broadcaster, this.moderator, {
  limit: 1000,
});
```
where `this.moderator` resulted into the bot account and the API was then trying to use the bot account token and failing because the scope is missing.

~~To resolve this the 2nd argument of `getChatters` now gets the account passed that has the `chatters` intend (and therefore the `moderator:read:chatters` scope).~~
edit: I changed the implementation now to store the user id of the token that has the moderator:read:chatters scope and i removed the chatters intend and then used that user id to make the requests.

### Benefits

The queue can load chatters when a 2 token setup is used.
Otherwise only people who recently chatted count as being online.

### Potential drawbacks

~~The submitted code is not ideal, but I think we should merge this just to have the `develop` branch fixed and then later create a better solution.~~
edit: Changed to the better solution and there are no drawbacks that I know of.

### CODE REVIEW

**Comment by liquidnya** [comment]
I changed the implementation now to store the user id of the token that has the `moderator:read:chatters` scope and i removed the `chatters` intend.
The intend is not really needed since `getChatters` always uses the token of the user id of the 2nd argument!

**Comment by liquidnya** [comment]
I manually tested this with a 2 token setup.
I did not test it with just a bot token (neither where the broadcaster is the bot token nor where the bot token is just used alone).

**Comment by liquidnya** [comment]
Specifically I tested it with the following setup:
Broadcaster token with scopes: channel:manage:redemptions channel:read:redemptions channel:read:subscriptions moderation:read moderator:read:chatters
Bot token with scopes: chat:edit chat:read

**Comment by liquidnya** [comment]
Also works with a bot (that is not the broadcaster) token with the following scopes:
chat:read chat:edit moderator:read:chatters

**Comment by liquidnya** [comment]
Also works with a bot = broadcaster token with the scopes:
channel:manage:redemptions channel:read:redemptions channel:read:subscriptions chat:edit chat:read moderation:read moderator:read:chatters

**Comment by demize** [comment]
> I changed the implementation now to store the user id of the token that has the `moderator:read:chatters` scope and i removed the `chatters` intend. The intend is not really needed since `getChatters` always uses the token of the user id of the 2nd argument!

Eh, I think we should probably keep using the intents system through Twurple here. Tracking the user with chatters permission specifically might be slightly more efficient, but it comes at the cost of adding a second system with the same purpose.

That is, our code will overall be simpler (and easier to work with and understand) if we only have the one system for identifying which token is needed for which scope. If that all goes through Twurple, we know (and anyone trying to understand our code knows) that when we establish a new permission it's added as an intent, and when we need to get a token for a specific permission it can be done through Twurple. If we start adding in a second system and using it for some permissions, then we lose that simplicity.

We could probably improve how we use the intent system through Twurple to make things that much more clear, but I don't see much benefit for us in moving away from it unless we're going to migrate away from it fully.

**Comment by liquidnya** [comment]
I just removed the `chatters` intend, as the intend is ignored when calling `getChatters`.
From it's function signature:
> The token of this user will be used to fetch the chatters.

One thing we could do is revert back one commit of this PR where it is using intends, since Twurple does not give us any way of using intents with `getChatters` we could just fetch the user id that fulfills the intent ourselves like I was doing here:
https://github.com/fluid-queue/fluid-queue/pull/115/commits/8cb947a1aba4280c8eca44506606f2b54eba0be9#diff-20dbd8769c13012d5cc8a66961ec1d72ed63d51e933ef06ad236e0060b4914abR303-R311

Then we would use intents again for chatters, however the previous code was already tracking different user IDs and I was thinking why track both user ID and intent when the user ID is sufficient in this case.

**Comment by liquidnya** [comment]
I reverted the changes and cleaned up the code a bit. It is now using the `chatters` intent again to get the user ID.

**Review by demize — APPROVED** [review]
Alright, LGTM.

Would be nice if Twurple provided a less awkward way to provide the moderator here, but this keeps it about as simple as we can on our end.

**Pull request merged**
