### PR TITLE
Remove dashes when printing an OCW code, and update tests to expect that

### LINKED ISSUE #62: OCW codes are printed with dashes, which prevents copy and paste
We should probably just make it print the codes without dashes, though still accept dashes in code entry. Or maybe make this an option you can toggle.

### PR DESCRIPTION
**Pull request by demize**
### Checklist

- [X] Have you followed the guidelines in our Contributing document?
- [X] Have you run `eslint` on the code and resolved any errors?
- [X] Have you run `npm test` and all tests are passing?
- [X] Have you added new tests for any new functions created?
- [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

Remove dashes from OCW level codes when printing them (closes #62).

### Benefits

Easier copy and paste of OCW codes.

### Potential drawbacks

Harder to read the codes?

### CODE REVIEW

**Comment by demize** [comment]
Not done with this yet. Want to try to figure out how to print the URL too, since that would be pretty nice.

**Comment by liquidnya** [comment]
I wonder if we should make this a setting or if it doesn't really make sense to have such a setting, because it will probably not be used.

**Comment by demize** [comment]
Adding an option for it would be nice, but I don't think it would see a lot of use, especially if I can figure out how to print the URL as well (since that will have dashes). I'll think more on it.

**Comment by demize** [comment]
Tried to figure out how to print the URL, but I don't really see any way to do it without forcing a breaking change.

I think I came up with a nice system to add options to resolvers, though.

**Review by liquidnya — CHANGES_REQUESTED** [review]
The changes look good to me and I like how you introduced generic options for extensions, however I think `resolverOptions` is not a good name, because the resolvers for ocw are actually `ocw` and `ocw-lenient`. I would suggest naming it `queueEntryOptions`, since those options are used in the `display` function of the queue entry or naming it `extensionsOptions` or just `extensions` and grouping them by extension name and making those options available to extensions (and not just resolvers and display functions of queue entries).

**Comment by demize** [comment]
Renamed it to `extensionOptions`. It should already be available to anything that includes `settings.js`, and already grouped by extension name (just the only option in there right now is extensionOptions->ocw->removeDashes for OCW codes).

**Pull request merged**
