### PR TITLE
Upgrade to node LTS 20

### PR DESCRIPTION
**Pull request by liquidnya**
### Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you run `eslint` on the code and resolved any errors?
- [x] Have you run `npm test` and all tests are passing?
- [ ] Have you added new tests for any new functions created?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

Updates to node version `20.9.0` (minimum) which is the new LTS version of node.
This also updates dependencies.

Notable changes:

- `jest-chance` was finally updated, see #131
- GitHub workflow now uses `20.x` and `21.x`
- `--loader` is no longer supported and is replaced by the register API, see https://github.com/swc-project/swc-node/issues/743
  This means that instead of `--loader @swc-node/register/esm` the following is used: `--import 'data:text/javascript,import{register as r}from\"node:module\";import{pathToFileURL as p}from\"node:url\";r(\"%40swc-node/register/esm\",p(\"./\"));'`. We could also move this code into a `.js` file like `register.js` that contains that JavaScript.
- Fixed compiler errors and formatting

I tested the following with docker:

- `docker compose -f docker-compose.test.yml up`
- `docker build .`

I tested the following with node `20.9.0` and `21.0.0`:
- `npm test`
- `npm run prepare`
- `npm run build`
- `npm run check`
- `npm run dist-build`

### Benefits

Updated dependencies and usage of the new LTS version.
Also the active support of node 18 ended. (But security support ends in about 1 year and 5 months from now)
As of now 0 vulnerabilities in dependencies.

### Potential drawbacks

People need to upgrade their node version.
This might introduce bugs.
`npm run start:swc` does not work any more. → I may or may not investigate this further, but we could also just drop support of this. (As this is only meant for developing the queue anyways)

### CODE REVIEW

**Comment by demize** [comment]
> We could also move this code into a .js file like register.js that contains that JavaScript.

Yeah, we should probably do something like this instead. Don't like having an opaque blob in the command line like that.

**Comment by liquidnya** [comment]
> > We could also move this code into a .js file like register.js that contains that JavaScript.
> 
> Yeah, we should probably do something like this instead. Don't like having an opaque blob in the command line like that.

I added a `register-swc.js` file (which is also needed for docker) and fixed `start:swc` by changing the `file://` URL to a path.
This might break running the bot under windows which need to be tested still.

**Comment by liquidnya** [comment]
I fixed the windows build.
For some reason `@swc-node/register` in version `1.6.8` does not work on Windows, so I reverted it to `1.6.7`.
Building, starting and testing works on windows now.
Also the `import()` function only allows `file://` URLs on Windows.

I wonder if version `1.6.8` also breaks the usage of `file://` URLs on Linux.

**Comment by liquidnya** [comment]
> I wonder if version `1.6.8` also breaks the usage of `file://` URLs on Linux.
Yes! Using `pathToFileURL(importArg).toString()` on Linux works with `npm run start:swc` again!
Which means that `@swc-node/register` in version `1.6.8` breaks the import of `file://` URLs on Linux and also breaks Windows.

**Comment by demize** [comment]
@liquidnya any reason not to merge this now?

**Comment by liquidnya** [comment]
You can merge it now. The only thing I did not do is to re-do all the tests (as described in the first message of the PR) I did earlier before I changed more.
Other than that I think all issues have been resolved and I think it's stable enough for the develop branch.

**Review by demize — APPROVED** [review]

**Comment by demize** [comment]
I'll update the required CI checks, then merge.

**Pull request merged**
