### PR TITLE
Use YAML for parsing settings/settings.yml

### PR DESCRIPTION
**Pull request by liquidnya**
### Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you run `eslint` on the code and resolved any errors?
- [x] Have you run `npm test` and all tests are passing?
- [ ] Have you added new tests for any new functions created?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

Introducing the new settings file `settings/settings.yml` (as well as its example file) instead of `settings/settings.json`/`settings.json`.
Older files can still be loaded if the newer file(s) aren't present.
Note that all files are loaded as `YAML`.
Also adds a lot of comments to the settings file.

### Benefits

Comments in the example settings file. Hopefully making it better documented.

### Potential drawbacks

Maybe configuring YAML and comment out values might be more difficult than editing JSON?

### CODE REVIEW

**Comment by liquidnya** [comment]
Maybe the `.json` files should still be parsed as JSON opposed to always parsing any settings file with YAML.

**Comment by liquidnya** [comment]
Note that I also changed the `extensionOptions` to use `z.coerce.string()` for its values.
This means that you can configure `true` instead of `"true"`, but it will end up as `"true"` in both cases.

**Comment by liquidnya** [comment]
Should we also allow the file name `settings/settings.yaml`?

**Comment by demize** [comment]
> Maybe the `.json` files should still be parsed as JSON opposed to always parsing any settings file with YAML.

[John's concerns](https://john-millikin.com/json-is-not-a-yaml-subset) notwithstanding, the YAML parser should handle JSON fine, and any issues should be handled by `zod` since we're using it to make sure everything is typed correctly. YAML is definitely more ergonomic, so I'm in support of this change, but JSON is (enough of) a subset of YAML that we should be fine handling the JSON indefinitely.

We should absolutely encourage people to switch over, though.

> Should we also allow the file name settings/settings.yaml?

I don't see why not. `yml` is probably more popular, but it doesn't hurt to handle both.

**Comment by liquidnya** [comment]
I added the `.yaml` file extension (but `.yml` has priority) and parsed the `settings.json` files with `JSON` instead of `YAML`.

**Comment by liquidnya** [comment]
But people can just move their `settings.json` file to `settings/settings.yml` without modifying it if they wanted to.

**Review by demize — APPROVED** [review]
LGTM.

**Pull request merged**
