### PR TITLE
Add build version

### PR DESCRIPTION
**Pull request by liquidnya**
Check build version on startup

### Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you run `eslint` on the code and resolved any errors?
- [x] Have you run `npm test` and all tests are passing?
- [ ] Have you added new tests for any new functions created?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

This adds the version at build time to the esbuild output.
The queue in `build/index.js` will then print the build version and not the current version.
Also a warning is printed when the current version does not equal the build version.

I have only manually tested this:
- Tested that using `npm run start` will print the build version now
- Tested that using `npm run start` will print a warning if the build version does not equal the version in `package.json`
- Tested that using `npm run test` and `docker-compose -f docker-compose.test.yml up` will not print the version warning

### Benefits

It is easier to detect that one forgot to run `npm run build` after using `git pull` (or similar).
Running the queue will always print the real version and also warn the user in case the version does not match.

### Potential drawbacks

Introducing more complexity at startup and also introducing 2 global (`var`) variables that are marked with `// eslint-disable-next-line no-var`.

### CODE REVIEW

**Comment by liquidnya** [comment]
For some reason importing `version.ts` from `src` fails with an error, but importing it from `lib` works.

**Comment by liquidnya** [comment]
This is still a draft, because I need to test all manual tests again!

**Comment by liquidnya** [comment]
I manually tested all tests again → It's now ready for review.

**Review by demize — APPROVED** [review]
LGTM. I'll note this will introduce a pretty rough merge conflict with #81, since it does a *lot* to package-lock.json. 

We might want to hold off on merging this until we merge #81, then rebase #86 off develop again once this is merged in (and the conflicts are resolved).

**Pull request merged**
